const {test}=require('node:test');
const assert=require('node:assert/strict');
const Store=require('../www/project-store.js');
function storage(initial={}){const data=new Map(Object.entries(initial));return {getItem:k=>data.get(k)??null,setItem:(k,v)=>data.set(k,String(v)),data};}
function fixture(){return {title:'Projeto original',characters:[{name:'Ana',extra:'preservar'}],episodes:[{number:7,title:'Sete',script:null},{number:1,title:'Um',script:{hook:'Gancho original',providersUsed:['Groq'],scenes:[{id:'a',place:'Casa',time:'Dia',action:'Ação original',dialogue:[{name:'Ana',text:'Linha um\nLinha dois: texto',emotion:'medo'}],videoClipUrl:'https://example.com/a.mp4',localClip:{key:'blob-a',name:'a.mp4'},custom:{important:true}},{id:'b',place:'Rua',action:'Ação dois',dialogue:[]}]}}],memory:['Fato original'],storyBible:{rules:'Não alterar nomes'}};}
const patch={place:'Praça',time:'Noite',action:'Nova ação manual',dialogue:[{name:'Ana',text:'Olá'}],duration:8};
test('seleção por número funciona em episódios fora de ordem e não contíguos',()=>{const p=fixture();assert.equal(Store.episode(p,1).title,'Um');assert.equal(Store.episode(p,7).title,'Sete');assert.throws(()=>Store.episode(p,2));});
test('todos os episódios podem receber várias cenas, inclusive sem roteiro',()=>{const p=fixture();for(const number of [1,7]){Store.updateScene(p,number,null,patch);Store.updateScene(p,number,null,patch);}assert.equal(Store.scenes(p,1).length,4);assert.equal(Store.scenes(p,7).length,2);assert.equal(Store.episode(p,1).script.hook,'Gancho original');});
test('edição preserva id, metadados, URLs e arquivo local da cena',()=>{const p=fixture();Store.updateScene(p,1,0,patch);const s=Store.scenes(p,1)[0];assert.equal(s.id,'a');assert.equal(s.localClip.key,'blob-a');assert.equal(s.videoClipUrl,'https://example.com/a.mp4');assert.deepEqual(s.custom,{important:true});assert.equal(Store.episode(p,1).script.providersUsed[0],'Groq');});
test('reordenação move a cena inteira e mantém vínculo do clipe',()=>{const p=fixture();assert.equal(Store.moveScene(p,1,0,1),true);assert.deepEqual(Store.scenes(p,1).map(s=>s.id),['b','a']);assert.equal(Store.scenes(p,1)[1].localClip.key,'blob-a');assert.equal(Store.moveScene(p,1,0,-1),false);});
test('exclusão confirmada é reversível sem perder roteiro ou clipes',()=>{const p=fixture(),original=Store.clone(Store.scenes(p,1));Store.removeScene(p,1,0);assert.equal(Store.scenes(p,1).length,1);Store.restoreScene(p,1);assert.deepEqual(Store.scenes(p,1),original);});
test('salvamento conserva cenas e outras temporadas após reiniciar',()=>{const p=fixture(),s=storage();Store.snapshot(p);p.seasons['2']={episodes:[{number:1,script:{scenes:[{id:'season2',action:'Não apagar'}]}}],memory:['T2'],extra:'preservar'};Store.updateScene(p,7,null,patch);Store.save(s,p);const restored=Store.projects(s)[0];assert.equal(Store.scenes(restored,7).length,1);assert.equal(restored.seasons['1'].episodes[1].script.scenes.length,2);assert.equal(restored.seasons['2'].episodes[0].script.scenes[0].id,'season2');assert.equal(restored.storyBible.rules,'Não alterar nomes');});
test('snapshot preserva propriedades desconhecidas de temporada',()=>{const p=fixture();Store.snapshot(p);p.seasons['1'].custom='conservar';Store.snapshot(p);assert.equal(p.seasons['1'].custom,'conservar');});
test('criar outro projeto não apaga projeto legado ou roteiros existentes',()=>{const old=fixture(),raw=JSON.stringify(old),s=storage({[Store.LEGACY]:raw}),newProject=fixture();newProject.title='Novo';newProject.episodes=[];Store.save(s,newProject);assert.equal(Store.projects(s).length,2);assert.equal(s.getItem('doramaOriginalV13'),raw);assert.equal(Store.projects(s).find(p=>p.title==='Projeto original').episodes[1].script.scenes.length,2);});
test('JSON legado inválido é preservado em backup ao salvar outro projeto',()=>{const s=storage({[Store.LEGACY]:'{invalid-json'});Store.save(s,fixture());assert.equal(s.getItem('doramaOriginalV13'),'{invalid-json');});
test('biblioteca corrompida bloqueia gravação em vez de sobrescrever dados',()=>{const s=storage({[Store.LIBRARY]:'{"broken":'});assert.throws(()=>Store.save(s,fixture()));assert.equal(s.getItem(Store.LIBRARY),'{"broken":');});
test('falha de quota não sobrescreve biblioteca nem atribui identidade não salva',()=>{const p=fixture(),s=storage();Store.save(s,p);const original=s.getItem(Store.LIBRARY);const next=fixture();s.setItem=(key,value)=>{if(key===Store.LIBRARY)throw Error('QuotaExceededError');s.data.set(key,value);};assert.throws(()=>Store.save(s,next),/Quota/);assert.equal(s.getItem(Store.LIBRARY),original);assert.equal(next.localId,undefined);});
test('exportação inclui todas as cenas na ordem atual sem alterar roteiro',()=>{const p=fixture();Store.moveScene(p,1,0,1);const before=JSON.stringify(p),plan=Store.plan(p,1);assert.equal(plan.scenes.length,2);assert.deepEqual(plan.scenes.map(s=>s.id),['b','a']);assert.deepEqual(plan.scenes.map(s=>s.order),[1,2]);assert.equal(plan.scenes[1].dialogue[0].text,'Linha um\nLinha dois: texto');assert.equal(plan.scenes[1].custom.important,true);assert.equal(plan.cliffhanger,'Gancho original');plan.scenes[0].place='alterar cópia';assert.equal(JSON.stringify(p),before);});
test('entrada inválida não altera roteiro existente',()=>{const p=fixture(),before=JSON.stringify(p);assert.throws(()=>Store.updateScene(p,1,0,{...patch,duration:NaN}));assert.throws(()=>Store.updateScene(p,1,10,patch));assert.throws(()=>Store.updateScene(p,1,0,{...patch,action:''}));assert.equal(JSON.stringify(p),before);});
test('não inventa cenas ao salvar ou exportar episódio vazio',()=>{const p=fixture(),s=storage();Store.save(s,p);assert.deepEqual(Store.plan(p,7).scenes,[]);assert.equal(Store.episode(Store.projects(s)[0],7).script,null);});
